### ISSUE TITLE
Add feature to include specific "key" or "value" to labels

### ISSUE THREAD

**Issue by eatskolnikov** [christianhelle/ScrollableSegmentedControl#10]
Each segment should have an individual identifier set by the user.
One use case of this is If the user can only have access to a specific 'tab' the tab validation would be pretty hard to be done by index since you would never be sure on which index is a specific tab going to appear.

Also, the UISegmentedControl has this feature, if someone is migrating from that control to this one, having this feature would make it easier.

For the implementation I suggest adding a new class called "Segment" with two properties: Title and Value.
For the class "ScrollableSegmentedControl" include the properties: "SelectedSegment" and "SelectedValue"

This might require some refactoring, I'm willing to do it myself after a confirmation ;p

**Comment by christianhelle** [comment]
First of all thanks for the input. 

Unfortunately, it's been a while... I wrote this 5 or 6 years ago and I haven't touched Xamarin.iOS for 2 years. My re-learning curve would probably be a bit steep, to say the least

If you have time and you pretty much know exactly what to do then please give it a go :)

**Comment by christianhelle** [comment]
At the time of writing this component, it was a 1-to-1 port of [HMSegmentedControl](https://github.com/HeshamMegid/HMSegmentedControl). After looking at my CV and [this blogpost](https://christian-helle.blogspot.com/2019/06/scrollable-uisegmentedcontrol-for.html) I can see that this has been ages ago. The original component seems to still being kept somewhat up-to-date so re-aligning with that might be cool one day

**Comment by eatskolnikov** [comment]
Thanks for the response, I'll get to work on this specific feature this week.

Mind reviewing a PR I opened before?
