### ISSUE TITLE
App crashes when I add the segmented control to an additional view instead of the base view.

### ISSUE THREAD

**Issue by ezhao1** [christianhelle/ScrollableSegmentedControl#7]
Hey, thanks for making this port. I have a problem - it works fine if I follow the example and add the segmented control to the base view, but when I try to add it to a subview of the base view, for some reason it will cause the app to crash a few seconds later (although it will successfully display segmented controller there). Here's the errors I get:

> dynamic_cast error 2: One or more of the following type_info's  has hidden visibility.  They should all have public visibility.   N10__cxxabiv116__shim_type_infoE, id, N10__cxxabiv117__pbase_type_infoE.

> Encountered an uncaught exception. All Mixpanel instances were archived.

Would appreciate any help. Thanks!

**Comment by ezhao1** [comment]
Okay, I figured out the problem. It wasn't because I was adding to a subview, it was because the function for setting up the segmented controller was being called twice in succession. Making sure it was only called once seemed to fix the problem.

**Comment by christianhelle** [comment]
I'm glad you find it useful and its great that you found a solution yourself
